config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'task#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task

  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to:'taks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create #POST /restaurant
  raise
  @task = Task.new(params_task)

  if @task.save
  redirect_to task_path(@task)
  else
  render :new, status:  :unprocessable_entity
  end

  def edit
  @task = Task.find(params[:id])
  end

  private

  def params_task
  params.require(:task).permit()
  end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>To Do List</h1>
<ul style="list-style: none">
  <% @tasks.each do |task| %>
    <li><input type="checkbox" name="" id=""><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>
<button><%= link_to "crear task", new_task_path %></button>

app/views/tasks/new.html.erb
<%= form_with model: @task do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div>
      <%= form.label :details %>
      <%= form.text_area :details %>
    </div>
    <div>
      <%= form.label :completed %>
      <%= form.check_box :completed %>
    </div>
    <div>
      <%= form.submit "Create Task" %>
    </div>
  <% end %>
  <%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="d-flex align-items-center card p-3">
  <div class="card-body">
    <div class="card-title">
      <h2><%= @task.title %></h2>
    </div>
    <div class="card-text">
      <%= @task.details %>
    </div>
    <div class="card-link">
      <%= link_to "Back to the Tasks", tasks_path %>
    </div>
  </div>
</div>